

name: Prod Back End Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build and Deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
         
          cd /home/ubuntu/AnonChats
          git pull origin main
          git status
          bash /home/ubuntu/kill_server.sh
          nohup python3 server.py > output.log 2>&1 &
          pgrep -f -x "python3 server.py"
        
